# Exception Handling


# num1 = 5 
# num2 = 1
# try:
#     print(num1/num2)
# except:
#     print("Error")
# Try Except Finally

# try:
    # In try block we write the part of code that may raise an error 
# except:
    # In except block we write the code that is to be executed if error occurs in try block finally:
    # The  code of finally block runs even if error occurs or not. Basically it always gets executed.
# while True:
#     try:
        
#         num1 = int(input("Enter the 1st number:"))
#         num2 = int(input("Enter the 2nd number:"))

#         print(num1/num2)
#         break
#     except ZeroDivisionError as e:
#         print(e)
#     except ValueError:
#         print("You have entered wrong data type!")

# list = [1,2,3,4,5]
# try:
#     print(list[5])
# except  IndexError as e:
#     print(e)

# try:
#     file = open("abc.txt","r")
#     content = file.read()
#     file.close
# except FileNotFoundError as e:
#     file = open("abc.txt","w")
#     file.close()    




































































































